spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  flyway:
    enabled: false

web3j:
  client-address: "ws://localhost:8545"
  contract:
    address: "0x0000000000000000000000000000000000000000"
    start-block: "latest"

logging:
  level:
    com.web3.eventmonitor: DEBUG
